### ISSUE TITLE
rust supports windows, so does pen have plans to support windows?

### ISSUE THREAD

**Issue by fenginsc** [pen-lang/pen#1748]
rust supports windows, so does pen have plans to support windows?

**Comment by raviqqe** [comment]
BTW, you can run Pen at least on WSL 2.

**Comment by fenginsc** [comment]
Ok, I would try to run it with WSL2 first, I don't know your language very well yet, so I may not be able to offer to help you compile the windows version.

**Comment by raviqqe** [comment]
Thank you! I appreciate any contribution and even feedback!
