### ISSUE TITLE
Failure building hello-world example

### ISSUE THREAD

**Issue by farmerzhang1** [pen-lang/pen#1955]
Hi, interesting project!
I'm having some trouble building the hello world example. I cloned the source from github and built it manually, but when I tried building something the build failed without much clear information.
```
farmerzhang1@DESKTOP-SPSMT3N:~/pen$ pen create foo
farmerzhang1@DESKTOP-SPSMT3N:~/pen$ cd foo
farmerzhang1@DESKTOP-SPSMT3N:~/pen/foo$ pen build
error: build failed
farmerzhang1@DESKTOP-SPSMT3N:~/pen/foo$ pen build --verbose
info: initializing external packages
info: building modules
error: build failed
```
could it be ninja that's failing the building process? just guessing. my ninja version is 1.10.0
many thanks!

**Comment by raviqqe** [comment]
Actually, the latest version of Pen shouldn't run Ninja but it runs Turtle, which is its drop-in replacement instead.

How did you install Pen? Which OS do you use? It seems to work on my laptop.
