### ISSUE TITLE
JSON library package

### ISSUE THREAD

**Issue by raviqqe** [pen-lang/pen#396]
# Problem

- It's difficult to serialize or deserialize data from and into JSON.

# Solution

- Provide a standard package of JSON serialization/deserialization.

**Comment by sammy-hughes** [comment]
Does Rust's approach have value as reference, having a generalized package for parsing, with specific parsers pre-implemented?

**Comment by raviqqe** [comment]
@sammy-hughes Definitely!

If we want performance almost comparable to other system programming languages like Rust, we probably want something like [`StringBuilder`](https://docs.oracle.com/javase/7/docs/api/java/lang/StringBuilder.html) or some way to introduce mutable states and traverse primitive or user-defined data types with reflection (as the language don't have generics.)

**Comment by sammy-hughes** [comment]
As an immutable parser, I was thinking a numeric iterator indexing the byte-array source or list comprehension over the input as a byte-array. For better UTF8 support, the numeric iterator might be designed to contain a start and stop offsets to describe a given, but single-byte ASCII assumed here for logic. I'm not clear on whether type aliasing is permitted or even a desirable feature, but I will assume it for purpose of describing logic succinctly.

Encoders and Decoders could be implemented with a list of classifier statemachine functions implemented by the importer.

Decode from string:
1. input, as raw bytes.
2. mapping closure, to give indices as two-value, index+codepoint records, used in a list-comprehension
3. a filter function, to reduce the above list comprehension to structural characters
4. a state-machine classifier that matches pairs of structural symbols on a stack, followed by a slice of the list of index+codepoint pairs that occur between them. Callbacks needed would be to resolve and fail, taking the codepoint encountered and returning a bool, recurse, taking a new state and the codepoint stream sliced at the current codepoint, and returning a structured value with the number of codepoints parsed, and a string-or-none error message.

Encode as string:
Input as structured, native values, of static types that can be resolved to a record, a list, or one of the JSON primitives. All other elements should yield an error-type return.
1. input as structured values.
2. non-tail-call-recursively resolve inner-to-outer values into bytearrays, producing an error-type value instead if a given instance cannot be encoded using any packaged or registered encoder.
3. collect as a list comprehension for each return. Alternatively a step-2.5 could run through collecting a length to reserve, and collections can be implemented behind the scenes into the preallocated slice.

**Comment by raviqqe** [comment]
Thanks for the detailed description!

So in my understanding, state machine resolver functions in the decoding part need to know all the types statically. And users need to the decoded values like `Json` values of maps, arrays, etc. into their own user-defined types. Is that correct?

**Comment by sammy-hughes** [comment]
I finally got around to making a stab at the trace-and-parse approach I described. The reference to a "statemachine" parser was a misnomer. I think the model resembles a weighted constraint dependency grammar, with the fixed variation in relative rule applicators modeled as state-machine transitions.

https://github.com/sammy-hughes/pen-encoding/tree/main/Heuristics

I'd like to raise some points about this experience, but that seems out of scope for this topic, so I'm pushing that to a discussion.

**Comment by raviqqe** [comment]
Hi, @sammy-hughes! Thank you so much for writing the example package. I'm gonna take a look at it soon.

Currently, Pen is waiting for LLVM 14 release in Homebrew because there is [a bug in LLVM 13 about tail call elimination](https://github.com/raviqqe/llvm-tail-call-opt-bug). Without LLVM 14 landing in Homebrew, we can't test new language features or packages unfortunately. So I've been working for the other subprojects like a code formatter and documentation generator recently. Hopefully, I can put more work on new language features and packages like serialization/deserialization soon!

**Comment by raviqqe** [comment]
@sammy-hughes I just took a look at your repo. Now, I grasp the concept better! Did you try to write any parsers or something with it?
