### ISSUE TITLE
Debug message declares 'package Core not found' -- package specific 

### ISSUE THREAD

**Issue by sammy-hughes** [pen-lang/pen#858]
I created and built a different package successfully, but this particular package throws an error when building. The error is obviously in error, but beyond that I'm not sure how to help you.
```
mybox:Heuristic me$ pen build --verbose
info: initializing external packages
info: building modules
compiling FFI module in .pen/default/packages/pen_prelude
resolving dependency of Trace.pen
error: package Core not found
error: build failed
```
Repo: https://github.com/sammy-hughes/pen-encoding

**Comment by raviqqe** [comment]
If the repository is up to date, it looks like you didn't add a dependency entry for a `Core` package. Can you try updating `pen.json` like [the examples in documentation](https://pen-lang.org/references/language/packages.html#examples)?

**Comment by sammy-hughes** [comment]
Oh. You are correct. I had forgotten to appropriately update the manifest! #spoiledRotten
